theme: jekyll-theme-minimal
title: "The art of text analysis"
description: "7 July 2022, 9 am - 5 pm | room: TBD, University of Canberra"
logo: "https://fraba.github.io/2022-ANZCA-workshop-The-art-of-text-analysis/img/logo.png"