theme: jekyll-theme-minimal
title: "Text mining and analysis"
description: "7 July 2022, 9 am - 5 pm | room: 5B55a and Room 5B55b, University of Canberra"
logo: "https://fraba.github.io/2022-ANZCA-workshop-The-art-of-text-analysis/img/logo.png"